import type { NicheConfig } from "@/types";

export const commercialCleaning: NicheConfig = {
  slug: "commercial-cleaning",
  name: "Commercial Cleaning",
  tagline: "Exclusive Commercial Cleaning Contracts",
  heroHeadline: "Get Matched With Exclusive Commercial Cleaning Contracts In Your Area",
  heroSubheadline: "We connect qualified cleaning businesses with verified contract opportunities — no cold calling, no bidding wars. Answer a few questions to see if you qualify.",
  ctaText: "Check My Eligibility →",
  accentColor: "#1d4ed8",
  spotsPerMonth: 12,
  socialProofCount: 847,
  socialProofLabel: "cleaning businesses matched this month",
  trustBadges: [
    "Verified Contract Opportunities",
    "No Bidding Wars",
    "Exclusive Territory",
    "Results in 30 Days",
  ],
  thankYouHeadline: "You're Pre-Qualified! 🎉",
  thankYouSubheadline: "One of our contract specialists will call you within 24 hours to discuss your contract matches. Check your email for next steps.",
  calendarUrl: "https://calendly.com/your-calendar-link",
  steps: [
    {
      id: "in_business",
      type: "option",
      question: "Are you currently operating a commercial cleaning business?",
      subtitle: "We only work with active cleaning operations",
      options: [
        { label: "Yes, actively operating", value: "yes", score: 20 },
        { label: "No, I'm just starting out", value: "no", score: 0, disqualify: true },
      ],
    },
    {
      id: "years_in_business",
      type: "option",
      question: "How long have you been in the commercial cleaning industry?",
      subtitle: "Experience helps us match you with the right contracts",
      options: [
        { label: "Less than 1 year", value: "under_1", score: 5, icon: "🌱" },
        { label: "1 – 3 years", value: "1_3", score: 15, icon: "📈" },
        { label: "3 – 5 years", value: "3_5", score: 25, icon: "⭐" },
        { label: "5+ years", value: "5_plus", score: 35, icon: "🏆" },
      ],
    },
    {
      id: "active_contracts",
      type: "option",
      question: "How many active commercial contracts do you currently hold?",
      subtitle: "Be honest — this helps us find the right opportunities for your capacity",
      options: [
        { label: "0 contracts (starting fresh)", value: "0", score: 5, icon: "0️⃣" },
        { label: "1 – 5 contracts", value: "1_5", score: 15, icon: "🔑" },
        { label: "6 – 15 contracts", value: "6_15", score: 25, icon: "💼" },
        { label: "15+ contracts", value: "15_plus", score: 35, icon: "🚀" },
      ],
    },
    {
      id: "services",
      type: "multiselect",
      question: "Which services do you currently offer?",
      subtitle: "Select all that apply — more services = more contract options",
      options: [
        { label: "Office / Workspace Cleaning", value: "office", score: 10 },
        { label: "Floor Care & Maintenance", value: "floors", score: 10 },
        { label: "Restroom Sanitation", value: "restroom", score: 8 },
        { label: "Window Cleaning", value: "windows", score: 8 },
        { label: "Medical / Healthcare Facilities", value: "medical", score: 15 },
        { label: "Industrial / Warehouse", value: "industrial", score: 12 },
        { label: "Post-Construction Cleanup", value: "post_construction", score: 10 },
        { label: "Day Porter Services", value: "day_porter", score: 8 },
      ],
    },
    {
      id: "monthly_revenue",
      type: "option",
      question: "What is your current average monthly revenue from cleaning contracts?",
      subtitle: "This stays confidential and helps us find contracts that fit your growth stage",
      options: [
        { label: "Under $5,000/month", value: "under_5k", score: 5, icon: "💵" },
        { label: "$5,000 – $15,000/month", value: "5k_15k", score: 15, icon: "💰" },
        { label: "$15,000 – $30,000/month", value: "15k_30k", score: 25, icon: "💎" },
        { label: "$30,000+/month", value: "30k_plus", score: 35, icon: "🏦" },
      ],
    },
    {
      id: "licensed_insured",
      type: "option",
      question: "Is your business currently licensed and insured?",
      subtitle: "All contract opportunities require proper licensing and liability insurance",
      options: [
        { label: "Yes — licensed & insured", value: "yes", score: 20 },
        { label: "Working on it (pending)", value: "pending", score: 5 },
        { label: "No, not yet", value: "no", score: 0, disqualify: true },
      ],
    },
    {
      id: "staff_size",
      type: "option",
      question: "How many cleaning staff / technicians do you have?",
      subtitle: "Staff capacity determines which contract sizes we match you with",
      options: [
        { label: "Just me (solo operator)", value: "solo", score: 5, icon: "🙋" },
        { label: "1 – 5 employees", value: "1_5", score: 15, icon: "👥" },
        { label: "6 – 15 employees", value: "6_15", score: 25, icon: "🏢" },
        { label: "15+ employees", value: "15_plus", score: 35, icon: "🏗️" },
      ],
    },
    {
      id: "biggest_challenge",
      type: "option",
      question: "What is your #1 challenge in growing your cleaning business right now?",
      subtitle: "We use this to prioritize the right type of contract matches for you",
      options: [
        { label: "Finding new contracts / clients", value: "contracts", score: 10, icon: "🔍" },
        { label: "Cash flow & predictable income", value: "cashflow", score: 10, icon: "💸" },
        { label: "Hiring & managing staff", value: "staffing", score: 8, icon: "👷" },
        { label: "Scaling & systemizing operations", value: "scaling", score: 12, icon: "📊" },
      ],
    },
    {
      id: "revenue_goal",
      type: "option",
      question: "What monthly revenue goal are you targeting in the next 6 months?",
      subtitle: "We'll match you with contract volumes that can hit this target",
      options: [
        { label: "$10,000 – $25,000/month", value: "10k_25k", score: 10, icon: "🎯" },
        { label: "$25,000 – $50,000/month", value: "25k_50k", score: 20, icon: "📈" },
        { label: "$50,000 – $100,000/month", value: "50k_100k", score: 30, icon: "🚀" },
        { label: "$100,000+/month", value: "100k_plus", score: 35, icon: "💫" },
      ],
    },
    {
      id: "contact",
      type: "contact",
      question: "Almost done! Where should we send your contract matches?",
      subtitle: "Your information is 100% confidential and never sold to third parties",
    },
  ],
};
